import './globals.css';

import Lnb from '@/widgets/Lnb/ui/Lnb';
import { MSWProvider } from './providers/MSWProvider';
import type { Metadata } from 'next';
import localFont from 'next/font/local';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MSWProvider />
        <Lnb />
        <main className="px-4 py-8 flex justify-center items-center flex-1 md:ml-33 transition-all duration-300 ease-in-out">
          {children}
        </main>
      </body>
    </html>
  );
}
